### ISSUE TITLE
Syntax highlighting of LSL on Github

### ISSUE THREAD

**Issue by buildersbrewery** [Dbz/Networked-Share-Vendor#1]
Hello @Dbz,

as I've provided Github with files to highlight the Linden Scripting Language correctly, it would help if you removed the `.html` from the `*.lsl` files to make use of the described functionality.

Happy coding!

**Comment by Dbz** [comment]
Hello! It's nice to see someone look at this project. I haven't been on SL for a very long time. I've updated the readme to use markdown, and I've updated the extensions of the files. Thank you for adding support for the `.lsl` extension.
